# Generated by Django 3.0.6 on 2020-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('unit', models.CharField(choices=[('TAB', 'Tablet'), ('SYP', 'Syrup'), ('INJ', 'Injection'), ('CAP', 'Capsule'), ('DROP', 'Drop'), ('TIN', 'Tin'), ('PCS', 'PCS'), ('POWE', 'POWE')], max_length=4)),
                ('stock', models.IntegerField(default=0)),
                ('cost_price', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
                ('sales_price', models.IntegerField(default=0)),
                ('m_r_p', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
